import "%modules%/header/header";
import "%modules%/main/main";
import "%modules%/service/service";
// import "%modules%/main/main_full";
//import "%modules%/nav-dot/nav-dot";
import "%modules%/molds/molds";
import "%modules%/numbers/numbers";
import "%modules%/request/request";
import "%modules%/stages/stages";
import "%modules%/examples/examples";
import "%modules%/examples-all/examples-all";
import "%modules%/examples/fresco";
import "%modules%/examples-all/fresco-all";
import "%modules%/advantages/advantages";
import "%modules%/partners/partners";
import "%modules%/gallery/gallery";
// import "%modules%/molds/molds";
// import "%modules%/team/team";
// import "%modules%/client/client";
import "%modules%/make/make";
// import "%modules%/review/review";
import "%modules%/contacts/contacts";
import "%modules%/footer/footer";
import "%modules%/form/form";
import "%modules%/form/mail";