import "%modules%/header/header";
import "%modules%/nav-dot/nav-dot";
import "%modules%/numbers/numbers";
import "%modules%/stages/stages";
import "%modules%/make/make";
import "%modules%/review/review";
import "%modules%/contacts/contacts";
import "%modules%/footer/footer";
import "%modules%/form/form";